### PR TITLE
Add yaml file path and module number as daq options

### PR DESCRIPTION
**Pull request by artlbv**
Adding options for the hexaboard test

**DO NOT MERGE** since it might get updated

### CODE REVIEW

**Comment by artlbv** [comment]
@asteencern in principle, these changes (except for the different default configs) could be taken over the master python branch

**Comment by adavidzh** [comment]
Pulling this will also close #9.
@artlbv, I would only suggest that we may want to get all `yaml`s in a `conf` directory to avoid clutter.
Otherwise 👍, thanks.
(We can deal with the refactoring of `run_local.py` and the `daq-zmq-client.py` later.)

**Comment by artlbv** [comment]
@adavidzh I've moved the yaml and sk2cms configs to a separate folder. Should just check this before merging (especially the `import config.skiroc2cms_bit_string as sk2conf`). I could also delete/reset today's configs and leave just one default

**Comment by adavidzh** [comment]
@artlbv, I think that we should keep other configurations as it does not hurt and can be useful in the future.

**Comment by artlbv** [comment]
@asteencern is this PR still needed? The main idea was to make the module number and config files as arguments

**Pull request closed without merging**
